In [25]:
import numpy as np
import pandas as pd

Add filter to filter all charts by year



*   Rename the filter title to “Select Year:”

Bar chart showing Absolute Discount per Country per Opportunity Type

* Add chart title
*  Apply a custom chart colour (rgb(35, 61, 77))
*   
remove axis titles
*   remove legend
*   remove gridlines

Bar chart showing Absolute Discount by Product Category/ Product Name
*   Sort by Product Category/ Product Name
*   Colour both charts by Product Category

rgb(207, 198, 100)

rgb(254, 127, 45)

rgb(252, 202, 70)

rgb(161, 193, 129)

rgb(97, 155, 138)


*   
Remove axis titles
*   
Remove legends

All numbers should be formatted as currency

In [26]:
df=pd.read_csv('/content/Wow-2023-02-Data (3).csv')
df

Absolute Discount Billing Country  Close Date Year  List Price  \
0                    0             USA             2029           0   
1               436275             USA             2029         450   
2               306600             USA             2029        1600   
3                 9070             USA             2029         100   
4                84600         Belgium             2029         550   
..                 ...             ...              ...         ...   
372              77100     Switzerland             2028        1000   
373             264400     Switzerland             2028         600   
374             385400          Canada             2029         800   
375             270400         Belgium             2029         800   
376              86600         Belgium             2029        1600   

          Opportunity Type Product Family    Product Name  Quantity  \
0    New Business / Add-on            NaN             NaN         0   
1        Existing Business         Phones   Space phone 2      1939   
2        Existing Business        Laptops      Pro laptop      1533   
3        Existing Business    Accessories        Keyboard       907   
4    New Business / Add-on         Phones   Space phone 3      1692   
..                     ...            ...             ...       ...   
372           New Business        Tablets  Light tablet 2       514   
373           New Business        Tablets     Mini tablet      1322   
374           New Business        Tablets    Light tablet      1927   
375  New Business / Add-on        Tablets    Light tablet      1352   
376  New Business / Add-on        Laptops      Pro laptop       433   

     Sales Price  Total List Price  Total Price  
0              0                 0            0  
1            225            872550       436275  
2           1400           2452800      2146200  
3             90             90700        81630  
4            500            930600       846000  
..           ...               ...          ...  
372          850            514000       436900  
373          400            793200       528800  
374          600           1541600      1156200  
375          600           1081600       811200  
376         1400            692800       606200  

[377 rows x 11 columns]

In [27]:
df.shape

(377, 11)

In [28]:
df.columns

Index(['Absolute Discount', 'Billing Country', 'Close Date Year', 'List Price',
       'Opportunity Type', 'Product Family', 'Product Name', 'Quantity',
       'Sales Price', 'Total List Price', 'Total Price'],
      dtype='object')

In [29]:
df['Billing Country'].unique()

array(['USA', 'Belgium', 'Switzerland', 'Canada', 'Taiwan', 'India',
       'Germany', 'Normway', 'Russian', 'Japan', 'Mexico', 'Brazil',
       'Singapore', 'Italy', 'Sweden', 'Australia', 'China', 'Hong Kong',
       'France', 'Turkey', 'United Kingdom', 'Spain', 'Thailand', 'Korea',
       'Denmark'], dtype=object)

In [30]:
df['Close Date Year'].unique()

array([2029, 2028])

In [31]:
df['Opportunity Type'].unique()

array(['New Business / Add-on', 'Existing Business', 'New Business'],
      dtype=object)

In [32]:
df['Product Family'].unique()

array([nan, 'Phones', 'Laptops', 'Accessories', 'Tablets',
       'Digital Media'], dtype=object)

In [33]:
df['Product Name'].unique()

array([nan, 'Space phone 2', 'Pro laptop', 'Keyboard', 'Space phone 3',
       'Notebook', 'Mouse', 'Light tablet', 'Cables', 'Light laptop',
       'Books', 'Mega laptop', 'Courses', 'Mini tablet', 'Mini tablet 2',
       'Certifications', 'Light tablet 2', 'Cases'], dtype=object)

In [34]:
df.isna().sum()

Absolute Discount     0
Billing Country       0
Close Date Year       0
List Price            0
Opportunity Type      0
Product Family       32
Product Name         32
Quantity              0
Sales Price           0
Total List Price      0
Total Price           0
dtype: int64

In [35]:
df[df['Product Family'].isna()]

Absolute Discount Billing Country  Close Date Year  List Price  \
0                    0             USA             2029           0   
5                    0     Switzerland             2029           0   
6                    0          Canada             2028           0   
32                   0           India             2028           0   
49                   0          Canada             2028           0   
55                   0         Russian             2029           0   
56                   0         Russian             2029           0   
67                   0           Japan             2029           0   
80                   0          Canada             2029           0   
94                   0       Australia             2029           0   
110                  0          Canada             2029           0   
111                  0             USA             2029           0   
112                  0       Hong Kong             2029           0   
117                  0          Turkey             2029           0   
122                  0           Japan             2029           0   
126                  0          Sweden             2029           0   
153                  0          Brazil             2029           0   
154                  0           Japan             2029           0   
171                  0  United Kingdom             2029           0   
201                  0           Italy             2029           0   
203                  0       Singapore             2028           0   
204                  0             USA             2028           0   
209                  0       Australia             2028           0   
243                  0       Australia             2029           0   
258                  0          Canada             2029           0   
285                  0         Denmark             2029           0   
286                  0          Sweden             2029           0   
308                  0           China             2029           0   
356                  0           China             2029           0   
363                  0           Spain             2029           0   
370                  0        Thailand             2029           0   
371                  0          Brazil             2029           0   

          Opportunity Type Product Family Product Name  Quantity  Sales Price  \
0    New Business / Add-on            NaN          NaN         0            0   
5             New Business            NaN          NaN         0            0   
6    New Business / Add-on            NaN          NaN         0            0   
32            New Business            NaN          NaN         0            0   
49            New Business            NaN          NaN         0            0   
55            New Business            NaN          NaN         0            0   
56       Existing Business            NaN          NaN         0            0   
67       Existing Business            NaN          NaN         0            0   
80       Existing Business            NaN          NaN         0            0   
94       Existing Business            NaN          NaN         0            0   
110           New Business            NaN          NaN         0            0   
111           New Business            NaN          NaN         0            0   
112  New Business / Add-on            NaN          NaN         0            0   
117           New Business            NaN          NaN         0            0   
122  New Business / Add-on            NaN          NaN         0            0   
126           New Business            NaN          NaN         0            0   
153           New Business            NaN          NaN         0            0   
154           New Business            NaN          NaN         0            0   
171           New Business            NaN          NaN         0            0   
201      Existing Business            NaN

In [36]:
df['Product Family'].replace(np.nan,'nan product family',inplace=True)

In [37]:
df['Product Name'].replace(np.nan,'nan product name',inplace=True)

In [38]:
df.isna().sum()

Absolute Discount    0
Billing Country      0
Close Date Year      0
List Price           0
Opportunity Type     0
Product Family       0
Product Name         0
Quantity             0
Sales Price          0
Total List Price     0
Total Price          0
dtype: int64

In [39]:
pip install openpyxl

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [40]:
writer = pd.ExcelWriter('output.xlsx')

In [41]:
# write dataframe to excel
df.to_excel(writer)

In [42]:
# save the excel
writer.save()
print('DataFrame is written successfully to Excel File.')

DataFrame is written successfully to Excel File.


### Now for visiualization......we use tableau

Below link shows the discount on the products for each country

https://public.tableau.com/views/SimpleDiscountDashboard/Simpledisountdashboard?:language=en-GB&:display_count=n&:origin=viz_share_link